joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

fl_effort:
  type: velocity_controllers/JointVelocityController
  joint: FL

fr_effort:
  type: velocity_controllers/JointVelocityController
  joint: FR

rl_effort:
  type: velocity_controllers/JointVelocityController
  joint: RL

rr_effort:
  type: velocity_controllers/JointVelocityController
  joint: RR