joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

rl_velocity:
  type: effort_controllers/JointVelocityController
  joint: RL
  pid: {p: 100.0, i: 0.01, d: 10.0}

rr_velocity:
  type: effort_controllers/JointVelocityController
  joint: RR
  pid: {p: 100.0, i: 0.01, d: 10.0}

left_steering_position:
  type: position_controllers/JointPositionController
  joint: front_left_steering_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

right_steering_position:
  type: position_controllers/JointPositionController
  joint: front_right_steering_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}